Controllers/AlterarSenhaController.cs
using CadastroDeContatos.Helper;
using CadastroDeContatos.Models;
using CadastroDeContatos.Repository;
using Microsoft.AspNetCore.Mvc;

namespace CadastroDeContatos.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuariorepositorio;
        private readonly ISessao _sessao;
        public AlterarSenhaController (IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _usuariorepositorio = usuarioRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarsenhamodel)
        {
            try
            {
                UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                alterarsenhamodel.Id = usuarioLogado.Id;
                if(ModelState.IsValid)
                {
                    _usuariorepositorio.AlterarSenha(alterarsenhamodel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    return View("Index", alterarsenhamodel);
                }

                return View("Index", alterarsenhamodel);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos alterar sua senha. Tente novamente, detalhe do erro: {erro.Message}";
                return View("Index", alterarsenhamodel);
            }
        }
    }
}

Views/AlterarSenha/Index.cshtml
@using CadastroDeContatos.Enums;
@model AlterarSenhaModel
@{
    ViewData["Title"] = "Alterar senha do Usuário";
}

<div class="text-center">

    <h1 class="display-4">Alterar senha do Usuário</h1>

</div>

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<form asp-controller="AlterarSenha" asp-action="Alterar" method="post">
    <div class="from-group">
        <label for="senhaAtual">Senha Atual</label>
        <input type="password" asp-for="SenhaAtual" class="form-control" placeholder="Digite a senha atual do Usuário">
        @Html.ValidationMessageFor(x => x.SenhaAtual)
    </div>
    <br />
    <div class="from-group">
        <label for="novaSenha">Nova Senha</label>
        <input type="password" asp-for="NovaSenha" class="form-control" placeholder="Digite a nova senha do Usuário">
        @Html.ValidationMessageFor(x => x.NovaSenha)
    </div>
    <br />
    <div class="from-group">
        <label for="confirmarSenha">Confirmar a Nova Senha</label>
        <input type="password" asp-for="ConfirmarNovaSenha" class="form-control" placeholder="Digite a confirmação da nova senha do Usuário">
        @Html.ValidationMessageFor(x => x.ConfirmarNovaSenha)
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Home" asp-action="Index" role="button">Voltar</a>
</form>